### ISSUE TITLE
Stop support for the sonnet.library in favor of the powerpc.library

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/SonnetAmiga#40]
Need to clean-up the repository.
- [x] remove sonnet.library
- [x] remove special wosdb
- [x] remove sonnetpatch
- [x] remove InitSonnet
- [x] remove VBCC enhancements (x.s / startup.s)
- [x] remove leftover references to IRA (we didn't reassemble in automated builds in a long time)
... more?

**Comment by rkujawa** [comment]
ACK.

**Comment by DvdBoon** [comment]
No hurry. I'm not sure if it actually works at the moment. Sonnet library,
 I mean.

Op maandag 24 april 2017 heeft Radosław Kujawa <notifications@github.com>
het volgende geschreven:

**Comment by rkujawa** [comment]
Most done in commits c6736a322f2d9703680937886f5d9ed6f90fffaf, a32246eb8824d0efd527728b79d26fb41d472f9c, 32e3d044babf7b9328b79a42e44a1f17ce1e9ec3.

I don't think removing wosdb is a good idea, since our wosdb has some enhancements over original (including Altivec support). I'll later switch it to normal WarpOS build instead of Sonnet-specific.

**Comment by rkujawa** [comment]
Also updated README.md to take latest changes into account c8f9465eba5cbfdf5764ffe0b3e2e8f366dab31f .

**Comment by DvdBoon** [comment]
Thanks for all the effort :-)

2017-04-26 10:31 GMT+02:00 Radosław Kujawa <notifications@github.com>:

**Comment by rkujawa** [comment]
The included wosdb now should also work, as it is built by standard WarpOS VBCC target. 459aaf6fe1de9a0698a8cdf15bf822dc28316f34
